### ISSUE TITLE
Need to give api credentials 

### ISSUE THREAD

**Issue by frostyasian** [frostyasian/Project1#38]
enabling the edamam logo onto the html

**Comment by ejhalpin** [comment]
whoever takes this on needs to place the credentials on the page somewhere. I think that whatever logo we have should be in the results div (like the cookbook icon that's there now - but I don't really like that logo) and the edamam attribution should go in the navbar on the left.

**Comment by frostyasian** [comment]
are we removing the logo to put the edamam attribution? i was thinking it could maybe go on the very bottom right of the screen, that way we have our logo "Recipe Box" and still have the min required to credit edamam. I dont think the slide out div would interfere with it either
