### ISSUE TITLE
user account/favorites control not visible after creating account

### ISSUE THREAD

**Issue by Mugwumper** [frostyasian/Project1#44]
When user creates new account the controls to manage the account and/or show hide the right side panel (typically favorites) is not visible.

Steps to Reproduce
- launch app
- click Welcome (top right)
- click Sign Up option in the Sign In panel that just opened
- enter field values for a new account and click "sign up"
At this point you should see the "Welcome" label disappear

Work around: 
Refresh the page - it will show the chosen username for the new account.

**Comment by ejhalpin** [comment]
this may be resolved. Approve EH-hf-6 and 7, git pull, and test. I'm fairly certain that this issues doesn't exist
